apiVersion: v1
kind: Namespace
metadata:
  name: custofrete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custofrete-deployment
  namespace: custofrete
  labels:
    app: custofrete
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: custofrete
  template:
    metadata:
      labels:
        app: custofrete
    spec:
      containers:
        - name: custofrete
          image: petcompufrgs/custodofrete:staging
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: custofrete-service
  namespace: custofrete
spec:
  selector:
    app: custofrete
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: custofrete-ingress
  namespace: custofrete
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
    - host: custodofrete.tk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: custofrete-service
                port: 
                  number: 80
  tls:
    - hosts:
      - custodofrete.tk
      secretName: custofrete-tls